// Seed Data for Chat Demo
import { Conversation, Message } from './chatTypes';

export function generateSeedConversations(orgId: string, currentUserId: string): Conversation[] {
  const now = new Date().toISOString();
  
  return [
    {
      conversationId: 'c_general',
      orgId,
      type: 'channel',
      title: 'General',
      subtitle: 'Organization-wide announcements and discussion',
      participants: [currentUserId, 'user_ops', 'user_strategist', 'user_analyst'],
      linked: { projectId: null, clientId: null, taskId: null, recordId: null },
      lastMessageAt: new Date(Date.now() - 3600000).toISOString(),
      lastMessagePreview: 'Great work on the energy bill analysis everyone! 👏',
      unreadBy: { [currentUserId]: 2 },
      createdAt: now,
      updatedAt: now,
      version: 1,
    },
    {
      conversationId: 'c_campaign_ops',
      orgId,
      type: 'channel',
      title: 'Campaign Ops',
      subtitle: 'Campaign operations and coordination',
      participants: [currentUserId, 'user_ops', 'user_strategist'],
      linked: { projectId: null, clientId: null, taskId: null, recordId: null },
      lastMessageAt: new Date(Date.now() - 7200000).toISOString(),
      lastMessagePreview: 'Updated the door-knocking schedule for District 12',
      unreadBy: {},
      createdAt: now,
      updatedAt: now,
      version: 1,
    },
    {
      conversationId: 'c_dm_ops',
      orgId,
      type: 'dm',
      title: 'Operations Manager',
      subtitle: '',
      participants: [currentUserId, 'user_ops'],
      linked: { projectId: null, clientId: null, taskId: null, recordId: null },
      lastMessageAt: new Date(Date.now() - 1800000).toISOString(),
      lastMessagePreview: 'Can you review the budget proposal when you get a chance?',
      unreadBy: { [currentUserId]: 1 },
      createdAt: now,
      updatedAt: now,
      version: 1,
    },
    {
      conversationId: 'c_project_campaign',
      orgId,
      type: 'project',
      title: 'Project: District 12 Campaign Services',
      subtitle: 'Campaign management and coordination',
      participants: [currentUserId, 'user_ops', 'user_strategist'],
      linked: { projectId: 'proj_campaign_d12', clientId: 'client_smith', taskId: null, recordId: null },
      lastMessageAt: new Date(Date.now() - 900000).toISOString(),
      lastMessagePreview: 'Updated door count progress: 2,847 / 15,000 doors',
      unreadBy: {},
      createdAt: now,
      updatedAt: now,
      version: 1,
    },
    {
      conversationId: 'c_system_insights',
      orgId,
      type: 'system',
      title: 'Revere Insights',
      subtitle: 'AI-powered insights and activity feed',
      participants: [currentUserId],
      linked: { projectId: null, clientId: null, taskId: null, recordId: null },
      lastMessageAt: new Date(Date.now() - 300000).toISOString(),
      lastMessagePreview: '⚠️ District 12 Campaign: Door pace 18% behind target',
      unreadBy: { [currentUserId]: 3 },
      createdAt: now,
      updatedAt: now,
      version: 1,
    },
  ];
}

export function generateSeedMessages(orgId: string, currentUserId: string): Message[] {
  const now = Date.now();
  
  return [
    // General Channel Messages
    {
      messageId: 'm_gen_1',
      conversationId: 'c_general',
      orgId,
      senderUserId: 'user_strategist',
      senderName: 'Sarah Chen',
      senderAvatarUrl: null,
      kind: 'text',
      text: 'Team, we have a major legislative opportunity coming up. The energy reform bill is going to committee next week.',
      attachments: [],
      mentions: [],
      tags: [],
      linked: { projectId: null, taskId: null, billId: 'bill_energy_reform', legislatorId: null, recordId: null },
      replyToMessageId: null,
      reactions: { '👍': ['user_ops', currentUserId], '🔥': [currentUserId] },
      pinned: true,
      createdAt: new Date(now - 86400000).toISOString(),
      editedAt: null,
      version: 1,
    },
    {
      messageId: 'm_gen_2',
      conversationId: 'c_general',
      orgId,
      senderUserId: 'user_ops',
      senderName: 'Mike Rodriguez',
      senderAvatarUrl: null,
      kind: 'text',
      text: 'Good timing. I\'ll coordinate with our contacts on the Energy Committee.',
      attachments: [],
      mentions: [],
      tags: [],
      linked: { projectId: null, taskId: null, billId: null, legislatorId: null, recordId: null },
      replyToMessageId: 'm_gen_1',
      reactions: {},
      pinned: false,
      createdAt: new Date(now - 82800000).toISOString(),
      editedAt: null,
      version: 1,
    },
    {
      messageId: 'm_gen_3',
      conversationId: 'c_general',
      orgId,
      senderUserId: currentUserId,
      senderName: 'Will Davis',
      senderAvatarUrl: null,
      kind: 'text',
      text: 'Great work on the energy bill analysis everyone! 👏',
      attachments: [],
      mentions: [],
      tags: [],
      linked: { projectId: null, taskId: null, billId: null, legislatorId: null, recordId: null },
      replyToMessageId: null,
      reactions: { '🎉': ['user_strategist', 'user_ops'] },
      pinned: false,
      createdAt: new Date(now - 3600000).toISOString(),
      editedAt: null,
      version: 1,
    },

    // Campaign Ops Messages
    {
      messageId: 'm_camp_1',
      conversationId: 'c_campaign_ops',
      orgId,
      senderUserId: 'user_ops',
      senderName: 'Mike Rodriguez',
      senderAvatarUrl: null,
      kind: 'text',
      text: 'Updated the door-knocking schedule for District 12',
      attachments: [
        {
          type: 'link',
          label: 'View Schedule',
          url: '#',
          meta: { documentType: 'schedule' },
        },
      ],
      mentions: [currentUserId],
      tags: ['urgent'],
      linked: { projectId: 'proj_campaign_d12', taskId: null, billId: null, legislatorId: null, recordId: null },
      replyToMessageId: null,
      reactions: { '✅': [currentUserId] },
      pinned: false,
      createdAt: new Date(now - 7200000).toISOString(),
      editedAt: null,
      version: 1,
    },

    // DM Messages
    {
      messageId: 'm_dm_1',
      conversationId: 'c_dm_ops',
      orgId,
      senderUserId: 'user_ops',
      senderName: 'Mike Rodriguez',
      senderAvatarUrl: null,
      kind: 'text',
      text: 'Can you review the budget proposal when you get a chance?',
      attachments: [
        {
          type: 'link',
          label: 'Budget Proposal Q1 2024.pdf',
          url: '#',
          meta: { size: '2.4 MB' },
        },
      ],
      mentions: [],
      tags: ['FYI'],
      linked: { projectId: null, taskId: null, billId: null, legislatorId: null, recordId: null },
      replyToMessageId: null,
      reactions: {},
      pinned: false,
      createdAt: new Date(now - 1800000).toISOString(),
      editedAt: null,
      version: 1,
    },

    // Project Thread Messages
    {
      messageId: 'm_proj_1',
      conversationId: 'c_project_campaign',
      orgId,
      senderUserId: 'user_strategist',
      senderName: 'Sarah Chen',
      senderAvatarUrl: null,
      kind: 'comment',
      text: 'We need to accelerate the door-knocking pace. Currently at 19% with only 2 weeks left.',
      attachments: [],
      mentions: [currentUserId, 'user_ops'],
      tags: ['urgent'],
      linked: { projectId: 'proj_campaign_d12', taskId: null, billId: null, legislatorId: null, recordId: null },
      replyToMessageId: null,
      reactions: { '👀': [currentUserId, 'user_ops'] },
      pinned: false,
      createdAt: new Date(now - 7200000).toISOString(),
      editedAt: null,
      version: 1,
    },
    {
      messageId: 'm_proj_2',
      conversationId: 'c_project_campaign',
      orgId,
      senderUserId: currentUserId,
      senderName: 'Will Davis',
      senderAvatarUrl: null,
      kind: 'action_card',
      text: 'Task created: "Recruit 5 additional canvassers for District 12"',
      attachments: [],
      mentions: [],
      tags: [],
      linked: { projectId: 'proj_campaign_d12', taskId: 'task_recruit_canvassers', billId: null, legislatorId: null, recordId: null },
      replyToMessageId: 'm_proj_1',
      reactions: {},
      pinned: false,
      createdAt: new Date(now - 3600000).toISOString(),
      editedAt: null,
      version: 1,
    },
    {
      messageId: 'm_proj_3',
      conversationId: 'c_project_campaign',
      orgId,
      senderUserId: 'user_ops',
      senderName: 'Mike Rodriguez',
      senderAvatarUrl: null,
      kind: 'comment',
      text: 'Updated door count progress: 2,847 / 15,000 doors',
      attachments: [],
      mentions: [],
      tags: [],
      linked: { projectId: 'proj_campaign_d12', taskId: null, billId: null, legislatorId: null, recordId: null },
      replyToMessageId: null,
      reactions: {},
      pinned: false,
      createdAt: new Date(now - 900000).toISOString(),
      editedAt: null,
      version: 1,
    },

    // System/Insights Messages
    {
      messageId: 'm_sys_1',
      conversationId: 'c_system_insights',
      orgId,
      senderUserId: 'system_revere',
      senderName: 'Revere',
      senderAvatarUrl: null,
      kind: 'pythia_insight',
      text: '⚠️ **Door Pace Alert**: District 12 Campaign is 18% behind target pace.\n\n**Current Progress**: 2,847 / 15,000 doors (19%)\n**Days Remaining**: 14\n**Required Daily Rate**: 867 doors/day\n**Current Rate**: 203 doors/day\n\n**Recommendation**: Increase canvassing team by 4-5 volunteers or extend timeline by 3 weeks.',
      attachments: [],
      mentions: [currentUserId],
      tags: ['alert'],
      linked: { projectId: 'proj_campaign_d12', taskId: null, billId: null, legislatorId: null, recordId: null },
      replyToMessageId: null,
      reactions: { '🚨': [currentUserId] },
      pinned: true,
      createdAt: new Date(now - 14400000).toISOString(),
      editedAt: null,
      version: 1,
    },
    {
      messageId: 'm_sys_2',
      conversationId: 'c_system_insights',
      senderUserId: 'system_revere',
      senderName: 'Revere',
      text: '⚠️ District 12 Campaign: Door pace 18% behind target\n\n**Current Rate**: 42 doors/hr (target: 50)\n**Projected Shortfall**: 1,200 doors by Saturday\n\n💡 *Recommendation*: Add 2 canvassers to evening shift or extend hours to 8pm',
      kind: 'pythia_insight',
      reactions: {},
      pinned: false,
      replyToMessageId: null,
      attachments: [],
      linked: { projectId: 'p1', clientId: null, taskId: null, recordId: null },
      createdAt: new Date(Date.now() - 300000).toISOString(),
      version: 1,
    },
    {
      messageId: 'm_sys_3',
      conversationId: 'c_system_insights',
      orgId,
      senderUserId: 'system_revere',
      senderName: 'Revere',
      senderAvatarUrl: null,
      kind: 'pythia_insight',
      text: '📊 **Weekly Summary**: 12 tasks completed, 3 new project milestones reached, 5 bills tracked.',
      attachments: [],
      mentions: [],
      tags: [],
      linked: { projectId: null, taskId: null, billId: null, legislatorId: null, recordId: null },
      replyToMessageId: null,
      reactions: {},
      pinned: false,
      createdAt: new Date(now - 300000).toISOString(),
      editedAt: null,
      version: 1,
    },
  ];
}