/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "rosuumfoxoyfqkvklwog"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJvc3V1bWZveG95ZnFrdmtsd29nIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjYzNzgxMTQsImV4cCI6MjA4MTk1NDExNH0.mqyY16Mm5PKuEjGVvfBdXEiLzHhZuiJAWum12-7UpBg"
export const supabaseUrl = `https://${projectId}.supabase.co`
